### ISSUE TITLE
import dotenv from "dotenv-safe" error

### ISSUE THREAD

**Issue by TheTransparentRecruiter** [gragland/chatgpt-everywhere#33]
import dotenv from "dotenv-safe";
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Nevaehni** [comment]
Have the same error: 

import dotenv from "dotenv-safe";
       ^^^^^^

SyntaxError: Unexpected identifier
←[90m    at Module._compile (internal/modules/cjs/loader.js:720:23)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:643:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)←[39m        
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)←[39m      
←[90m    at internal/main/run_main_module.js:17:11←[39m

**Comment by agustinscigliano** [comment]
I had the same problem. Updating the node version fixed it.

**Comment by gragland** [comment]
Yes make sure to update to the latest version of Node if you're seeing this error

**Comment by TheTransparentRecruiter** [comment]
I just downloaded node for the first time a week ago, it should be the latest version, no?
